#!/bin/sh
#
# Load ALSA loopback device
#

case "$1" in
    start)
        printf "Loading snd-aloop: "
        modprobe snd-aloop
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
    stop)
        printf "Unloading snd-aloop: "
        rmmod snd-aloop
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
    restart|reload)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit 0

