#!/bin/sh
#
# Start jackd
#

NAME="jackd"
DAEMON="/usr/bin/$NAME"
PIDFILE="/var/run/$NAME.pid"
LOGFILE="/var/log/$NAME.log"
USER=snappi:audio

[ -r /etc/default/$NAME ] && . /etc/default/$NAME

case "$1" in
    start)
        printf "Starting $DAEMON: "
        ulimit -r unlimited -l unlimited
        start-stop-daemon -b -S -m -O "$LOGFILE" -c "$USER" -p "$PIDFILE" --exec "$DAEMON" \
            -- $JACKD_OPTS
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
    stop)
        printf "Stopping $DAEMON: "
        start-stop-daemon -K -q -p "$PIDFILE" -x "$DAEMON"
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
    restart|reload)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit 0
