#!/bin/sh
#
# Start jacktrip
#

NAME="jacktrip"
DAEMON="/usr/bin/$NAME"
PIDFILE="/var/run/$NAME.pid"
LOGFILE="/var/log/$NAME.log"
USER=snappi:audio

[ -r /etc/default/$NAME ] && . /etc/default/$NAME
JACKTRIP_OPTS="-s $JACKTRIP_OPTS"

[ -r /etc/snappi.conf ] && . /etc/snappi.conf
JACKTRIP_OPTS="$JACKTRIP_OPTS --receivechannels $SNAPPI_CHANNELS"

case "$1" in
    start)
        printf "Starting $NAME: "
        ulimit -r unlimited -l unlimited
        start-stop-daemon -b -S -m -O "$LOGFILE" -c "$USER" -p "$PIDFILE" --exec "$DAEMON" \
            -- $JACKTRIP_OPTS
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
    stop)
        printf "Stopping $NAME: "
        start-stop-daemon -K -q -p "$PIDFILE" -x "$DAEMON"
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
    restart|reload)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit 0

