#! /bin/sh

NAME=ina219
DAEMON=/usr/bin/$NAME
PIDFILE=/var/run/$NAME/pid

start() {
	echo -n "Starting $NAME: "
    modprobe i2c-dev
	start-stop-daemon -b --start --quiet --pidfile "$PIDFILE" --exec "$DAEMON"
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
	echo -n "Stopping $NAME: "
	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
	RETVAL="$?"
	[ "$RETVAL" = 2 ] && return 2
	rm -f $PIDFILE
	return "$RETVAL"
}

restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

