#! /bin/sh

[ -r /etc/snappi.conf ] && . /etc/snappi.conf

start() {
	echo "Configuring SnapServer"
    /usr/bin/snappiserver-config.py
}

stop() {
    :
}

restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

