#!/bin/sh

if [ ! -r /boot/user-data ] && [ ! -r /boot/network-.con ]; then
    exit 0
fi

start() {
	echo -n "Doing Snappi Cloud-Init"
    /usr/bin/snappi-cloud-init
    hostname -F /etc/hostname
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
	echo ""
}

restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
